stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - data/ 
  train:
    cmd: python train.py
    deps:
    - train.py
    - data/
    outs:
    - confusion_matrix.png
    metrics:
    - metrics.txt:
        cache: false