name: train-my-model
on: [push]
jobs:
  generate-report
  run:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - uses: iterative/setup-cml@v1
        - name: cml_run
           env:
              REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: |
              pip install -r requirements.txt
              python train.py

              cat metrics.txt >> report.md
              cml-publish confusion_matrix.png --md >> report.md
              cml-send-comment report.md