name: train-my-model
on: [push , pull_request]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run : gh api /repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/pulls
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Train model
        
        run: |
          pip3 install -r requirements.txt
          python train.py
          # Create CML report
          cml comment create --pr --publish metrics.txt
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
